### PR TITLE
Dependabot and PEP 621

### PR DESCRIPTION
**Pull request by LoicGrobol**
This adds dependabot to the repo, helping us keep our dependencies fresh. Due to bugfix creep, it also includes adding [PEP 621](https://peps.python.org/pep-0621) data to `pyproject.toml`, since setuptools has apparently [recently](https://github.com/pypa/setuptools/issues/3199) become more strict with it.

### CODE REVIEW

**Comment by abravalheri** [comment]
Hi @LoicGrobol, I am trying to understand this pattern of some projects using `pyproject.toml [project]` with a single config for `requires-python/python_requires`, to try to create a fix for setuptools.

Is this being used for a tool of some sort?

**Comment by LoicGrobol** [comment]
Hi @abravalheri, I am not sure what you are asking.

**Comment by abravalheri** [comment]
I saw that the having a `pyproject.toml` with only `requires-python` in the `[project]` table seems to be a recurring pattern in a few projects.

I was trying to understand if this happens because all these projects use some kind of tool that depends on the value of ``requires-python`` being set in `pyproject.toml`. Do you know anything about that?

Do you know why does ``hopsparser`` currently have it set, but without the other values from PEP 621?

**Comment by LoicGrobol** [comment]
@abravalheri Oh, I see. Well, I have trying to track down why, but the best I found is https://github.com/hopsparser/hopsparser/commit/f675894b so no real clue here, sorry. Probably I pasted it from **somewhere** but I can't recall where or why.

**Comment by abravalheri** [comment]
Thank you very much @LoicGrobol for at least having a look :)
I will try to find other hints on the internet

**Pull request merged**
